AppDevGCD0805/Controllers/CategoriesController.cs
using AppDevGCD0805.Data;
using AppDevGCD0805.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AppDevGCD0805.Controllers
{
	public class CategoriesController : Controller
	{
		private ApplicationDbContext _db;
		public CategoriesController(ApplicationDbContext db)
		{
			_db = db;
		}

		public IActionResult Index()
		{

			return View(_db.Categories.ToList());
		}

		[HttpGet]
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Create(Category category)
		{
			_db.Categories.Add(category);
			_db.SaveChanges();

			return RedirectToAction("Index");
		}

		[HttpGet]
		public IActionResult Delete(int Id)
		{
			var categoryinDb = _db.Categories.SingleOrDefault(item => item.Id == Id);
			_db.Categories.Remove(categoryinDb);
			_db.SaveChanges();

			return RedirectToAction("Index");
		}

		[HttpGet]
		public ActionResult Edit(int id)
		{

			var todoInDb = _db.Categories
			  .SingleOrDefault(t => t.Id == id );
			
			return View(todoInDb);
		}

		[HttpPost]
		public ActionResult Edit(Category category)
		{
			var categoryinDb = _db.Categories.SingleOrDefault(item => item.Id == category.Id);
			categoryinDb.Name = category.Name;
			categoryinDb.Description = category.Description;

			_db.SaveChanges();

			return RedirectToAction("Index");
		}

	}
}

AppDevGCD0805/Controllers/CoursesController.cs
using System.Collections.Generic;
using System.Linq;
using AppDevGCD0805.Data;
using AppDevGCD0805.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace AppDevGCD0805.Controllers
{
    public class CoursesController : Controller
    {
        private ApplicationDbContext _db;
        public CoursesController(ApplicationDbContext db)
        {
            _db = db;
        }



        public ActionResult Index()
        {
            var model = _db.Courses.Include(x => x.Category);
            return View(model);
        }

        [HttpGet]

        public IActionResult Create()
        {
         //var model = _db.Categories.ToList();
         //ViewBag.name = model;
            var model = new Course();
            var cate = _db.Categories.ToList();
            var categoryList = _db.Categories.Select(x => new { x.Id, x.Name }).ToList();
            
            ViewBag.CategoryList = new SelectList(categoryList,"Id","Name");


            return View(model);
        }


        [HttpPost]
        public IActionResult Create(Course course)
        {
            _db.Courses.Add(course);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult Delete(int Id)
        {
            var courseinDb = _db.Courses.SingleOrDefault(item => item.Id == Id);
            _db.Courses.Remove(courseinDb);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {

         var todoInDb = _db.Courses
           .SingleOrDefault(t => t.Id == id);

         
         var model = new Course();
         var cate = _db.Categories.ToList();
         var categoryList = _db.Categories.Select(x => new { x.Id, x.Name }).ToList();

         ViewBag.CategoryList = new SelectList(categoryList, "Id", "Name");

   
         return View(todoInDb);
      }

        [HttpPost]
        public ActionResult Edit(Course course)
        {
            var courseinDb = _db.Courses.SingleOrDefault(item => item.Id == course.Id);
            courseinDb.Name = course.Name;
            courseinDb.Description = course.Description;
            courseinDb.CategoryId = course.CategoryId;

            _db.SaveChanges();

            return RedirectToAction("Index");
        }


    }
}

AppDevGCD0805/Controllers/TrainersController.cs
using AppDevGCD0805.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AppDevGCD0805.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace AppDevGCD0805.Controllers
{
   [Authorize(Roles = "Trainer")]

   public class TrainersController : Controller
	{
      private ApplicationDbContext _db;
      private readonly UserManager<User> _userManager;
      private readonly RoleManager<IdentityRole> _roleManager;

      public TrainersController(ApplicationDbContext db, UserManager<User> userManager, RoleManager<IdentityRole> roleManager)
      {
         _db = db;
         _userManager = userManager;
         _roleManager = roleManager;

      }
      // GET: Trainers
      [HttpGet]
      public ActionResult Index()
      {
         var userId = _userManager.GetUserId(User);
         var trainerinDb = _db.TrainerProfiles.Include(x=>x.User).SingleOrDefault(item => item.UserId == userId);
        
         return View(trainerinDb);
      }

      public ActionResult EditProfile(string Id)
      {

         var todoInDb = _db.TrainerProfiles.Include(x => x.User)
           .SingleOrDefault(item => item.UserId == Id);

         return View(todoInDb);
      }

      [HttpPost]
      public ActionResult EditProfile(TrainerProfile trainerProfile)
      {
         var userId = _userManager.GetUserId(User);
         var trainerinDb = _db.TrainerProfiles.Include(x => x.User).SingleOrDefault(item => item.UserId == userId);
         
         trainerinDb.User.FullName = trainerProfile.User.FullName;
         trainerinDb.User.Address = trainerProfile.User.Address;
         trainerinDb.User.Age = trainerProfile.User.Age;
         trainerinDb.Specialty = trainerProfile.Specialty;

         _db.SaveChanges();

         return RedirectToAction("Index");
      }

      public ActionResult ViewCourse(string? id)
      {
         string userId;
         if (id==null || id==string.Empty)
         {
            userId = _userManager.GetUserId(User);
         }
			else
			{
            userId = id;

         }
         var courseinDb = _db.AssignTrainerCourses.Include(x => x.Course).ThenInclude(x=>x.Category)
            .Where(x=>x.UserId==userId).ToList();

         return View(courseinDb);
      }

      public ActionResult ViewTrainee(int id)
      {
         var query = _db.TraineeProfiles.Include(x => x.AssignTraineeCourses).Include(x => x.User).AsQueryable();

         var traineeinDb = query.Where(x =>x.AssignTraineeCourses.Where(x=>x.CourseId==id).Any()).ToList(); 

         return View(traineeinDb);
      }
   }
}

AppDevGCD0805/Controllers/TrainingStaffsController.cs
using AppDevGCD0805.Data;
using AppDevGCD0805.Data.Migrations;
using AppDevGCD0805.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AssignTraineeCourse = AppDevGCD0805.Models.AssignTraineeCourse;
using AssignTrainerCourse = AppDevGCD0805.Models.AssignTrainerCourse;
using TraineeProfile = AppDevGCD0805.Models.TraineeProfile;

namespace AppDevGCD0805.Controllers
{
   [Authorize(Roles = "Staff")]
   public class TrainingStaffsController : Controller
   {
        private readonly UserManager<User> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        private ApplicationDbContext _db;
        public TrainingStaffsController(ApplicationDbContext db, UserManager<User> userManager, RoleManager<IdentityRole> roleManager)
        {
            _db = db;
            _userManager = userManager;
            _roleManager = roleManager;

        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CreateTrainee()
        {
            TraineeProfile model = new TraineeProfile();
            return View(model);
        }
        [HttpPost]
        public IActionResult CreateTrainee(TraineeProfile traineeProfile)
        {
            if (!ModelState.IsValid) return View(traineeProfile);

            if (_userManager.FindByEmailAsync(traineeProfile.User.Email).GetAwaiter().GetResult() != null)
            {
                TempData["Danger"] = "The email address is already registered";
                return View(new TraineeProfile());
            }
            var user = traineeProfile.User;
            user.UserName = user.Email;
            IdentityResult result = _userManager.CreateAsync(user, user.PasswordHash).GetAwaiter().GetResult();
            if (result.Succeeded)
            {
                _userManager.AddToRoleAsync(user, "Trainee").GetAwaiter().GetResult();
            }
            var trainee = new TraineeProfile();
            trainee.UserId = user.Id;
            trainee.DateOfBirth = traineeProfile.DateOfBirth;
            trainee.Education = traineeProfile.Education;

            _db.TraineeProfiles.Add(trainee);
            _db.SaveChanges();
            return RedirectToAction("ManageTrainee");
        }
        public IActionResult ManageTrainee()
        {
            var traineeinDB = _db.TraineeProfiles.Include(x => x.User).ToList();

            return View(traineeinDB);
        }
        public IActionResult Delete(string Id)
        {

            var staffindb = _db.Users.SingleOrDefault(item => item.Id == Id);
            _db.Users.Remove(staffindb);
            _db.SaveChanges();

            return RedirectToAction("ManageTrainee");
        }

        public ActionResult Edit(string Id)
        {

            var todoInDb = _db.TraineeProfiles.Include(x => x.User).SingleOrDefault(item => item.User.Id == Id);

            return View(todoInDb);
        }
        [HttpPost]
        public ActionResult Edit(TraineeProfile traineeProfile)
        {

           var traineeinDb = _db.TraineeProfiles.Include(x => x.User).SingleOrDefault(x => x.UserId == traineeProfile.User.Id);
           var user = _db.Users.SingleOrDefault(x => x.Id == traineeProfile.User.Id);
           user.FullName = traineeProfile.User.FullName;
           user.Address = traineeProfile.User.Address;
           user.Age = traineeProfile.User.Age;
           traineeinDb.DateOfBirth = traineeProfile.DateOfBirth;
           traineeProfile.Education = traineeProfile.Education;

           _db.SaveChanges();

           return RedirectToAction("ManageTrainee");
        }
        public ActionResult SearchTrainee(string searchString, int age)
        {
            var trainees = _db.TraineeProfiles.Include(x => x.User);
                        

            if (!String.IsNullOrEmpty(searchString))
            {
                var result = trainees.Where(s => s.User.FullName.Contains(searchString));
                
                if( age != 0)
                {
                    var final = result.Where(s => s.User.Age == age);
                    return View(final.ToList());
                }
                return View(result.ToList());
            }

            if (age != 0)
            {
                var final = trainees.Where(s => s.User.Age == age);
                return View(final.ToList());
            }
            return RedirectToAction("ManageTrainee");

        }
        public IActionResult ViewTrainer()
        {
           var trainerinDB = _db.TrainerProfiles.Include(x => x.User).ToList();
           return View(trainerinDB);
        }



        public ActionResult AssignTrainer(string id)
        {
           var model = new AssignTrainerCourse() { UserId=id };
           var trainers = _db.Users.SingleOrDefault(x => x.Id == id);
           ViewBag.User = trainers.FullName;
         
           var course = _db.Courses.ToList();
           var courseList = _db.Courses.Select(x => new { x.Id, x.Name }).ToList();

           ViewBag.CourseList = new SelectList(courseList, "Id", "Name");


           return View(model);

        }

      
        [HttpPost]
        public ActionResult AssignTrainer(AssignTrainerCourse assignTrainerCourse)
        {
            if (_db.AssignTrainerCourses.Find( assignTrainerCourse.UserId, assignTrainerCourse.CourseId) != null)
            {
                TempData["Danger"] = "The trainer was assigned to this course";
                return RedirectToAction("AssignTrainer",new { id=assignTrainerCourse.UserId});
            };
           _db.AssignTrainerCourses.Add(assignTrainerCourse);
           _db.SaveChanges();
           //return RedirectToAction("ViewCourse","Trainers", new {id = assignTrainerCourse.UserId });

           return RedirectToAction("ViewCourseTrainer","TrainingStaffs", new { id = assignTrainerCourse.UserId });
        }

        public ActionResult ViewCourseTrainer(string id)
        {

           var courseinDb = _db.AssignTrainerCourses.Include(x => x.Course).ThenInclude(x => x.Category)
              .Where(x => x.UserId == id).ToList();

           ViewBag.user = _db.Users.SingleOrDefault(x => x.Id == id);

           return View(courseinDb);
        }

        public IActionResult DeleteCourseTrainer(int Id, string userId)
        {

           var courseindb = _db.AssignTrainerCourses.SingleOrDefault(item => item.CourseId == Id && item.UserId==userId);
           _db.AssignTrainerCourses.Remove(courseindb);
           _db.SaveChanges();
           return RedirectToAction("ViewCourseTrainer", "TrainingStaffs", new { id = userId });
        }

        public IActionResult ViewTrainee()
        {
            var traineeinDB = _db.TraineeProfiles.Include(x => x.User).ToList();

            return View(traineeinDB);
        }
        public ActionResult AssignTrainee(string id)
        {
           var model = new AssignTraineeCourse() { UserId = id };
           var trainees = _db.Users.SingleOrDefault(x => x.Id == id);
           ViewBag.User = trainees.FullName;

           var course = _db.Courses.ToList();
           var courseList = _db.Courses.Select(x => new { x.Id, x.Name }).ToList();

           ViewBag.CourseList = new SelectList(courseList, "Id", "Name");


           return View(model);

        }
        public ActionResult ViewCourseTrainee(string id)
        {

           var courseinDb = _db.AssignTraineeCourses.Include(x => x.Course).ThenInclude(x => x.Category)
              .Where(x => x.UserId == id).ToList();

           ViewBag.user = _db.Users.SingleOrDefault(x => x.Id == id);

           return View(courseinDb);
        }
      
        [HttpPost]
        public ActionResult AssignTrainee(AssignTraineeCourse assignTraineeCourse)
        {
            if (_db.AssignTraineeCourses.Find(assignTraineeCourse.UserId, assignTraineeCourse.CourseId) != null)
            {
                TempData["Danger"] = "The trainee was assigned to this course";
                return RedirectToAction("AssignTrainee", new { id = assignTraineeCourse.UserId });
            };
            _db.AssignTraineeCourses.Add(assignTraineeCourse);
           _db.SaveChanges();
           //return RedirectToAction("ViewCourse","Trainers", new {id = assignTrainerCourse.UserId });

           return RedirectToAction("ViewCourseTrainee", "TrainingStaffs", new { id = assignTraineeCourse.UserId });
        }

        public IActionResult DeleteCourseTrainee(int Id, string userId)
        {

           var courseindb = _db.AssignTraineeCourses.SingleOrDefault(item => item.CourseId == Id && item.UserId == userId);
           _db.AssignTraineeCourses.Remove(courseindb);
           _db.SaveChanges();

           return RedirectToAction("ViewCourseTrainee", "TrainingStaffs", new { id = userId });
        }
        public ActionResult ViewUserInCourse()
        {
            var courses = _db.AssignTrainerCourses.Include(x => x.Course).Include(x => x.TrainerProfile).ThenInclude(x =>x.User).ToList(); 
            return View(courses);
        }

        public ActionResult TraineeInCourse(string searchString, string role)
        {
                return View();
        }
        public ActionResult SearchCourse(string searchString, string role)
        {
            var coursesTrainer = _db.AssignTrainerCourses.Include(x => x.Course).Include(x => x.TrainerProfile).ThenInclude(x => x.User);
            var coursesTrainee = _db.AssignTraineeCourses.Include(x => x.Course).Include(x => x.TraineeProfile).ThenInclude(x => x.User);

            if (!String.IsNullOrEmpty(searchString))
            {
                if( role == "trainer")
                {

AppDevGCD0805/Views/TrainingStaffs/AssignTrainee.cshtml
@model AppDevGCD0805.Models.AssignTraineeCourse



<h1>Create Course</h1>
<h1>Assign Course</h1>
@if (TempData["Danger"] != null)
{
    <div class="alert alert-danger alert-dismissable">
        <strong>@TempData["Danger"]</strong>
    </div>
}
<form asp-controller="TrainingStaffs" asp-action="AssignTrainee" method="post">
    <input hidden asp-for="@Model.UserId" />
    <div class="form-group">
        <label>Trainee</label>
        <p>@ViewBag.User</p>
    </div>


    <div class="form-group">
        <label>Course</label>

        @Html.DropDownListFor(model => model.CourseId, ViewBag.CourseList as SelectList,
                  "Select Course", new { @class = "form-control" })

    </div>

    <button type="submit" class="btn btn-outline-success">Create</button>

</form>
<br />
<center><a class="nav-link btn btn-outline-primary col-3 fas fa-reply" asp-controller="TrainingStaffs" asp-action="ViewTrainee">   Back to previous page</a></center>

AppDevGCD0805/Views/TrainingStaffs/AssignTrainer.cshtml
@model AppDevGCD0805.Models.AssignTrainerCourse



<h1>Assign Course</h1>
@if (TempData["Danger"] != null)
{
    <div class="alert alert-danger alert-dismissable">
        <strong>@TempData["Danger"]</strong>
    </div>
}
<form asp-controller="TrainingStaffs" asp-action="AssignTrainer" method="post">
    <input hidden asp-for="@Model.UserId" />
    <div class="card col-md-7">

        <div class="card-body">
            <div class="form-group card-header">
                <h5>Trainer : @ViewBag.User</h5>

            </div>
            <div class="form-group">
                <label>Course</label>
                <br />
                @Html.DropDownListFor(model => model.CourseId, ViewBag.CourseList as SelectList,
                          "Select Course", new { @class = "form-control col-md-5 btn btn-warning dropdown-toggle" })

            </div>

            <button type="submit" class="btn btn-outline-warning">Assign</button>

        </div>
    </div>
</form>
<br />

<center><a class="nav-link btn btn-outline-primary col-3 fas fa-reply" asp-controller="TrainingStaffs" asp-action="ViewTrainer">   Back to previous page</a></center>

AppDevGCD0805/Views/TrainingStaffs/CreateTrainee.cshtml
@model AppDevGCD0805.Models.TraineeProfile




<h1>Create Trainee</h1>
@if (TempData["Danger"] != null)
{
    <div class="alert alert-danger alert-dismissable">
        <strong>@TempData["Danger"]</strong>
    </div>
}
<form asp-controller="TrainingStaffs" asp-action="CreateTrainee" method="post">
    <div class="form-group">
        <label>Full Name</label>
        <input type="text" class="form-control" placeholder="Input full name" asp-for="User.FullName">
        <span asp-validation-for="User.FullName" class="text-danger"></span>

    </div>
    <div class="form-group">
        <label>Email</label>
        <input required type="email" class="form-control" placeholder="Input Email"
               asp-for="User.Email">
        <span asp-validation-for="User.Email" class="text-danger"></span>

    </div>
    <div class="form-group">
        <label>Password</label>
        <input required
               type="password" class="form-control" placeholder="Input Password" asp-for="User.PasswordHash" id="myInput">
        <br />
        <input type="checkbox" onclick="myFunction()">Show Password
    </div>
    <div class="form-group">
        <label>Age</label>
        <input type="text" class="form-control" placeholder="Input age" asp-for="User.Age">
    </div>

    <div class="form-group">
        <label>Address</label>
        <input type="text" class="form-control" placeholder="Input Address" asp-for="User.Address">
    </div>

    <div class="form-group">
        <label>Date of birth</label>
        <input type="date" class="form-control" placeholder="Input Date of birth" asp-for="DateOfBirth">
    </div>

    <div class="form-group">
        <label>Education</label>
        <input required type="text" class="form-control" placeholder="Input Education" asp-for="Education">
        <span asp-validation-for="Education" class="text-danger"></span>

    </div>
    <button type="submit" class="btn btn-outline-success">Create</button>
    <center><a class="nav-link btn btn-outline-primary col-3 fas fa-reply" asp-controller="TrainingStaffs" asp-action="Index">   Back to previous page</a></center>
</form>

AppDevGCD0805/Views/TrainingStaffs/Edit.cshtml
@model AppDevGCD0805.Models.TraineeProfile



<h1>Edit</h1>
@if (TempData["Danger"] != null)
{
    <div class="alert alert-danger alert-dismissable">
        <strong>@TempData["Danger"]</strong>
    </div>
}
<form asp-controller="TrainingStaffs" asp-action="Edit" method="post">
    <input hidden type="text" class="form-control" placeholder="Input full name" asp-for="User.Id">
    <div class="form-group">
        <label>Full Name</label>
        <input type="text" class="form-control" placeholder="Input full name" asp-for="User.FullName">
        <span asp-validation-for="User.FullName" class="text-danger"></span>

    </div>
    <div class="form-group">
        <label>Address</label>
        <input type="text" class="form-control" placeholder="Input address" asp-for="User.Address">
    </div>
    <div class="form-group">
        <label>Age</label>
        <input type="text" class="form-control" placeholder="Input age" asp-for="User.Age">
    </div>
    <div class="form-group">
        <label>Education</label>
        <input required type="text" class="form-control" placeholder="Input education" asp-for="Education">
        <span asp-validation-for="Education" class="text-danger"></span>

    </div>
    <div class="form-group">
        <label>Date Of Birth</label>
        <input type="date" class="form-control" placeholder="Input date of birth" asp-for="DateOfBirth">
    </div>
    <button type="submit" class="btn btn-outline-info">Edit</button>
</form>

AppDevGCD0805/Views/TrainingStaffs/Index.cshtml
<div class="jumbotron">
    <h1>FPT Training System</h1>
    <p class="lead">Welcome staff.</p>
</div>
<center><img src="~/staff.png" style="max-width: auto; max-height: auto" /></center>

<br />
<div class="card border-primary mb-3" style="max-width: 72rem">
    <div class="card-header">About training staff role</div>
    <div class="card-body text-primary">
        <p class="card-text">- Training staff can create and manage trainee accounts.</p>
        <p class="card-text">- Training staff can search for trainees by their name and age.</p>
        <p class="card-text">- Training staff can create and manage course category.</p>
        <p class="card-text">- Training staff can manage courses.</p>
        <p class="card-text">- Training staff can assign Trainers/ Trainees to a course. And can remove courses from Trainers/ Trainees.</p>
        <p class="card-text">- Training staff can search Trainers/ Trainees by entering Enrolled Course Name.</p>

    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="card border-success mb-3">
            <div class="card-header">Create Trainee account.</div>
            <div class="card-body text-success">
                <p class="card-text">Click the button below to create Trainee account.</p>
                <a class="nav-link btn btn-outline-success" asp-controller="TrainingStaffs" asp-action="CreateTrainee">Create</a>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card border-info mb-3">
            <div class="card-header">Management Trainee account.</div>
            <div class="card-body text-info">
                <p class="card-text">Click the button below to manage Trainee account.</p>
                <a class="nav-link btn btn-outline-info" asp-controller="TrainingStaffs" asp-action="ManageTrainee">Manage</a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="card border-primary mb-3">
            <div class="card-header">Manage Category.</div>
            <div class="card-body text-primary">
                <p class="card-text">Click the button below to manage Category.</p>
                <a class="nav-link btn btn-outline-primary" asp-controller="Categories" asp-action="Index">Manage</a>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card border-primary mb-3">
            <div class="card-header">Manage Course.</div>
            <div class="card-body text-primary">
                <p class="card-text">Click the button below to manage Category.</p>
                <a class="nav-link btn btn-outline-primary" asp-controller="Courses" asp-action="Index">Manage</a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="card border-warning mb-3">
            <div class="card-header">Assign Trainer.</div>
            <div class="card-body text-warning">
                <p class="card-text">Click the button below to assign Trainer.</p>
                <a class="nav-link btn btn-outline-warning" asp-controller="TrainingStaffs" asp-action="ViewTrainer">Assign</a>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card border-warning mb-3">
            <div class="card-header">Assign Trainee.</div>
            <div class="card-body text-warning">
                <p class="card-text">Click the button below to assign Trainee.</p>
                <a class="nav-link btn btn-outline-warning" asp-controller="TrainingStaffs" asp-action="ViewTrainee">Assign</a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="card border-secondary mb-3">
            <div class="card-header">View Trainer/Trainee in Course.</div>
            <div class="card-body text-secondary">
                <form asp-controller="TrainingStaffs" asp-action="SearchCourse" >
                    <div class="input-group ">
                        <input class="form-control mr-sm-2 " type="text" placeholder="Search by course " aria-label="Search" name="SearchString">
                        <input class="form-control mr-sm-2 " type="text" placeholder="Trainer/Trainee " aria-label="Search" name="role">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

AppDevGCD0805/Views/TrainingStaffs/ViewCourseTrainee.cshtml
@model ICollection<AppDevGCD0805.Models.AssignTraineeCourse>
@{
  ViewBag.Title = "View Course";
}

<h2>Course</h2>

@ViewBag.user.FullName

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Category</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    @foreach (var item in Model)
    {
    <tr>

      <td>@item.Course.Name</td>
      <td>@item.Course.Description</td>
      <td>@item.Course.Category.Name</td>

      <td>@Html.ActionLink("Delete", "DeleteCourseTrainee", "TrainingStaffs", new { id = item.CourseId, userId = item.UserId }, new { @class = "btn btn-danger" })</td>

    </tr>
    }

  </tbody>
</table>

AppDevGCD0805/Views/TrainingStaffs/ViewCourseTrainer.cshtml
@model  ICollection<AppDevGCD0805.Models.AssignTrainerCourse>
@{
  ViewBag.Title = "View Course";
}

<h2>Course of trainer</h2>


<div class="alert alert-primary col-md-4" role="alert">
    <h5>
        Trainer:
    </h5> 
    <center> @ViewBag.user.FullName</center>
   

</div>
<br />

<table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Name of course  </th>
            <th scope="col">Description</th>
            <th scope="col">Category</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
          <tr>
            <td>@Html.ActionLink(@item.Course.Name, "ViewTrainee", "Trainers", new { id = item.CourseId }, new { @class = "btn btn-success" })</td>

            <td>@item.Course.Description</td>
            <td>@item.Course.Category.Name</td>

            <td>@Html.ActionLink("Delete", "DeleteCourseTrainer", "TrainingStaffs", new { id = item.CourseId, userId = item.UserId }, new { @class = "btn btn-danger" })</td>

          </tr>
            }

        </tbody>
    </table>
<br />
<center><a class="nav-link btn btn-outline-primary col-3 fas fa-reply" asp-controller="TrainingStaffs" asp-action="ViewTrainer">   Back to previous page</a></center>