AppDevGCD0805/Controllers/AdminsController.cs
using AppDevGCD0805.Data;
using AppDevGCD0805.Models;
using AppDevGCD0805.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AppDevGCD0805.Controllers
{
   [Authorize(Roles = "Admin")]
   public class AdminsController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        private ApplicationDbContext _db;
        public AdminsController(ApplicationDbContext db, UserManager<User> userManager, RoleManager<IdentityRole> roleManager)
        {
            _db = db;
            _userManager = userManager;
            _roleManager = roleManager;

        }
        public IActionResult Index()
        {
            return View();
        }

        //Action Staff
        public IActionResult CreateStaff()
        {
            User model = new User();
            return View(model);
        }
        [HttpPost]
        public IActionResult CreateStaff(User user)
        {
            if (!ModelState.IsValid) return View(user);
            
            if (_userManager.FindByEmailAsync(user.Email).GetAwaiter().GetResult()!=null)
            {
                TempData["Danger"] = "The email address is already registered";
                return View(new User());
            }
            user.UserName = user.Email;
            
            IdentityResult result = _userManager.CreateAsync(user, user.PasswordHash).GetAwaiter().GetResult();

            if (result.Succeeded)
            {
               _userManager.AddToRoleAsync(user, "Staff").GetAwaiter().GetResult();
            }
            _db.SaveChanges();
            return RedirectToAction("ManageStaff");
        }
        public IActionResult ManageStaff()
        {
            
            var user = _userManager.GetUsersInRoleAsync("Staff").Result;
            return View(user);
        }
        [HttpGet]
        public IActionResult Delete(string Id)
        {
            
            var staffindb = _db.Users.SingleOrDefault(item => item.Id == Id);
            _db.Users.Remove(staffindb);
            _db.SaveChanges();

            return RedirectToAction("ManageStaff");
        }
        
        public ActionResult EditStaff(string Id)
        {

            var todoInDb = _db.Users
              .SingleOrDefault(item => item.Id == Id);

            return View(todoInDb);
        }

        [HttpPost]
        public ActionResult EditStaff(User user)
        {
            if (!ModelState.IsValid) return View(user);

            
            if (!ModelState.IsValid) return View(user);
            var staffinDb = _db.Users.SingleOrDefault(item => item.Id == user.Id);
            staffinDb.FullName = user.FullName;
            staffinDb.Address = user.Address;
            staffinDb.Age = user.Age;
            _db.SaveChanges();

            return RedirectToAction("ManageStaff");
        }


      //Action Trainer
      public IActionResult CreateTrainer()
        {
            TrainerProfile model = new TrainerProfile();
            return View(model);
        }
        [HttpPost]
        public IActionResult CreateTrainer(TrainerProfile trainerProfile)
        {

            if (!ModelState.IsValid) return View(trainerProfile);

            if (_userManager.FindByEmailAsync(trainerProfile.User.Email).GetAwaiter().GetResult() != null)
            {
                TempData["Danger"] = "The email address is already registered";
                return View(new TrainerProfile());
            }
            var user = trainerProfile.User;
            user.UserName = user.Email;
            IdentityResult result = _userManager.CreateAsync(user, user.PasswordHash).GetAwaiter().GetResult();
            
            if (result.Succeeded)
            {
               _userManager.AddToRoleAsync(user, "Trainer").GetAwaiter().GetResult();
            }
            var trainer = new TrainerProfile();
            trainer.UserId = user.Id;
            trainer.Specialty = trainerProfile.Specialty;
            
            _db.TrainerProfiles.Add(trainer);
            _db.SaveChanges();
            return RedirectToAction("ManageTrainer");
        }
        public IActionResult ManageTrainer()
        {
            var trainerinDB = _db.TrainerProfiles.Include(x => x.User).ToList();
            
            return View(trainerinDB);
        }

         public ActionResult EditTrainer(string Id)
         {

            var todoInDb = _db.Users
              .SingleOrDefault(item => item.Id == Id);

            return View(todoInDb);
         }

         [HttpPost]
         public ActionResult EditTrainer(User user)
         {
            
            var trainerinDb = _db.Users.SingleOrDefault(item => item.Id == user.Id);
            trainerinDb.FullName = user.FullName;
            trainerinDb.Address = user.Address;
            trainerinDb.Age = user.Age;

            _db.SaveChanges();

            return RedirectToAction("ManageTrainer");
         }
         public ActionResult ChangePassword(string userId)
         {
            return View();
         }
         [HttpPost]
         public ActionResult ChangePassword(ChangePasswordViewModel request )
         {
            var user = _db.Users.SingleOrDefault(x=>x.Id==request.UserId);
            _userManager.RemovePasswordAsync(user).GetAwaiter().GetResult();
            _userManager.AddPasswordAsync(user, request.NewPassword).GetAwaiter().GetResult();
            _db.SaveChanges();

            _userManager.GetRolesAsync(user);
            return RedirectToAction("ManageTrainer");
         }

      public IActionResult DeleteTrainer(string Id)
         {

            var trainerindb = _db.Users.SingleOrDefault(item => item.Id == Id);
            _db.Users.Remove(trainerindb);
            _db.SaveChanges();

            return RedirectToAction("ManageTrainer");
         }



   }

}

AppDevGCD0805/Controllers/TraineesController.cs
using AppDevGCD0805.Data;
using AppDevGCD0805.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AppDevGCD0805.Controllers
{
   [Authorize(Roles = "Trainee")]
   public class TraineesController : Controller
	{

      private ApplicationDbContext _db;
      private readonly UserManager<User> _userManager;
      private readonly RoleManager<IdentityRole> _roleManager;

      public TraineesController(ApplicationDbContext db, UserManager<User> userManager, RoleManager<IdentityRole> roleManager)
      {
         _db = db;
         _userManager = userManager;
         _roleManager = roleManager;

      }
      // GET: Trainees
      
      [HttpGet]
      public ActionResult Index()
      {
         var userId = _userManager.GetUserId(User);
         var traineeinDb = _db.TraineeProfiles.Include(x => x.User).SingleOrDefault(item => item.UserId == userId);

         return View(traineeinDb);
      }

      
     
      public ActionResult ViewCourse()
      {
         var userId = _userManager.GetUserId(User);
         var courseinDb = _db.AssignTraineeCourses.Include(x => x.Course).ThenInclude(x => x.Category).Where(x => x.UserId == userId).ToList();

         return View(courseinDb);
      }

      public ActionResult ViewTrainees(int id)
      {
         var query = _db.TraineeProfiles.Include(x => x.AssignTraineeCourses).Include(x => x.User).AsQueryable();

         var traineeinDb = query.Where(x => x.AssignTraineeCourses.Where(x => x.CourseId == id).Any()).ToList();

         return View(traineeinDb);
      }
   }
}

AppDevGCD0805/Controllers/TrainersController.cs
using AppDevGCD0805.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AppDevGCD0805.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace AppDevGCD0805.Controllers
{
   [Authorize(Roles = "Trainer")]

   public class TrainersController : Controller
	{
      private ApplicationDbContext _db;
      private readonly UserManager<User> _userManager;
      private readonly RoleManager<IdentityRole> _roleManager;

      public TrainersController(ApplicationDbContext db, UserManager<User> userManager, RoleManager<IdentityRole> roleManager)
      {
         _db = db;
         _userManager = userManager;
         _roleManager = roleManager;

      }
      // GET: Trainers
      [HttpGet]
      public ActionResult Index()
      {
         var userId = _userManager.GetUserId(User);
         var trainerinDb = _db.TrainerProfiles.Include(x=>x.User).SingleOrDefault(item => item.UserId == userId);
        
         return View(trainerinDb);
      }

      public ActionResult EditProfile(string Id)
      {

         var todoInDb = _db.TrainerProfiles.Include(x => x.User)
           .SingleOrDefault(item => item.UserId == Id);

         return View(todoInDb);
      }

      [HttpPost]
      public ActionResult EditProfile(TrainerProfile trainerProfile)
      {
         var userId = _userManager.GetUserId(User);
         var trainerinDb = _db.TrainerProfiles.Include(x => x.User).SingleOrDefault(item => item.UserId == userId);
         
         trainerinDb.User.FullName = trainerProfile.User.FullName;
         trainerinDb.User.Address = trainerProfile.User.Address;
         trainerinDb.User.Age = trainerProfile.User.Age;
         trainerinDb.Specialty = trainerProfile.Specialty;

         _db.SaveChanges();

         return RedirectToAction("Index");
      }

      public ActionResult ViewCourse(string? id)
      {
         string userId;
         if (id==null || id==string.Empty)
         {
            userId = _userManager.GetUserId(User);
         }
			else
			{
            userId = id;

         }
         var courseinDb = _db.AssignTrainerCourses.Include(x => x.Course).ThenInclude(x=>x.Category)
            .Where(x=>x.UserId==userId).ToList();

         return View(courseinDb);
      }

      public ActionResult ViewTrainee(int id)
      {
         var query = _db.TraineeProfiles.Include(x => x.AssignTraineeCourses).Include(x => x.User).AsQueryable();

         var traineeinDb = query.Where(x =>x.AssignTraineeCourses.Where(x=>x.CourseId==id).Any()).ToList(); 

         return View(traineeinDb);
      }
   }
}

AppDevGCD0805/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppDevGCD0805</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                
                <a class="navbar-brand">FPT</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Admin"))
                            {
                                <li>@Html.ActionLink("Home", "Index", "Admins")</li>
                            }
                            else if (User.IsInRole("Staff"))
                            {
                                <li>@Html.ActionLink("Home", "Index", "TrainingStaffs")</li>
                            }
                            else if (User.IsInRole("Trainer"))
                            {
                                <li>@Html.ActionLink("Home", "Index", "Trainers")</li>
                            }
                            else if (User.IsInRole("Trainee"))
                            {
                                <li>@Html.ActionLink("Home", "Index", "Trainees")</li>
                            }
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AppDevGCD0805 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>